Return 400 on /health when LB has zero hosts
Constellation-Labs/cllb pull request #16
Opened 2023-09-08 20:38 UTC by AlexBrandes

The current health check endpoint always returns a 200 response, even if there are no known hosts. This change returns a 400 response when no hosts are found so that the health checks can be properly responded to. Repeated health check failures will now cause ECS to trigger a new task to launch and kick off the node discovery process again. 

Tested locally.

2023-09-11 15:05 UTC, kpudlik requested changes

2023-09-11 15:05 UTC, kpudlik commented on src/main/scala/org/constellation/http/Loadbalancer.scala
> +            case 0 => BadRequest()
I am unsure if `400` is the appropriate status code as "Bad request" indicates that it is the client's fault, not the server's. Maybe we should use something from `5XX` family (we already use `503 Service unavailable` for LB's maintenance mode).

Also, keep in mind that `size` is set to `0` after the restart/rollback (double check if it is `0` or `3` or `1` in the beginning) so we may end up with the infinite restart-loop where one restart makes `size` equal `0` which then triggers another restart.

2023-09-11 15:49 UTC, AlexBrandes commented on src/main/scala/org/constellation/http/Loadbalancer.scala
> +            case 0 => BadRequest()
@kpudlik Thanks for the review. 

I agree on the `5XX` response probably being more proper although it doesn't really matter in this instance because the health check treats anything other than a `2XX` response as a failure. Is there a similar method to `BadRequest` to trigger a `5XX` response? 

The health check configuration requires 6 failed checks at 30 second intervals to trigger a restart so there's no danger of an infinite loop. 
https://github.com/Constellation-Labs/cllb/blob/health-check-zero-hosts/terraform/alb.tf#L46

2023-09-12 12:37 UTC, kpudlik commented on src/main/scala/org/constellation/http/Loadbalancer.scala
> +            case 0 => BadRequest()
>Is there a similar method to BadRequest to trigger a 5XX response?

Yes. Take a look at the `org.http4s.Status` package.

>The health check configuration requires 6 failed checks at 30 second intervals to trigger a restart so there's no danger of an infinite loop.

So at least one node needs to be discovered within 3 minutes. Sounds fine :+1:

2023-09-13 13:17 UTC, kpudlik approved these changes
Approved but keep in mind that load balancer should never have the upstream empty. I would consider returning `InternalServerError()` as a temporary solution to trigger "auto rollback of ELB" but the real cause of upstream being empty needs to be fixed anyway because such a situation is a bug.

2023-09-13 15:36 UTC, merged